extern const GeoLayout nos_tank_Wing_Cap_Switch_opt1[];
extern const GeoLayout nos_tank_geo[];
extern Lights1 nos_tank_NOS_Tank_lights;
extern u8 nos_tank_jer_tank_rgba16[];
extern u8 nos_tank_stainless_steel_i8[];
extern Vtx nos_tank_Wing_Cap_mesh_layer_1_vtx_0[79];
extern Gfx nos_tank_Wing_Cap_mesh_layer_1_tri_0[];
extern Vtx nos_tank_Wing_Cap_mesh_layer_1_vtx_1[18];
extern Gfx nos_tank_Wing_Cap_mesh_layer_1_tri_1[];
extern Gfx mat_nos_tank_NOS_Tank[];
extern Gfx mat_nos_tank_Steel[];
extern Gfx mat_revert_nos_tank_Steel[];
extern Gfx nos_tank_Wing_Cap_mesh_layer_1[];
extern Gfx nos_tank_material_revert_render_settings[];
