#include "src/game/envfx_snow.h"

const GeoLayout jer_afterimage_Opacity_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ASM(LAYER_OPAQUE + 3, geo_mario_set_player_colors),
		GEO_ASM(LAYER_OPAQUE_DECAL + 3, geo_mario_set_player_colors),
		GEO_ASM(LAYER_TRANSPARENT + 3, geo_mario_set_player_colors),
		GEO_ASM(LAYER_TRANSPARENT_DECAL + 3, geo_mario_set_player_colors),
		GEO_ASM(LAYER_OPAQUE << 2, geo_mirror_mario_backface_culling),
		GEO_ASM(LAYER_OPAQUE_DECAL << 2, geo_mirror_mario_backface_culling),
		GEO_ASM(LAYER_TRANSPARENT << 2, geo_mirror_mario_backface_culling),
		GEO_ASM(LAYER_TRANSPARENT_DECAL << 2, geo_mirror_mario_backface_culling),
		GEO_SWITCH_CASE(0, geo_switch_mario_stand_run),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 53, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 23, 0, 0, jer_afterimage_Butt_mesh_layer_3),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, jer_afterimage_Torso_skinned_mesh_layer_3),
						GEO_ASM(0, geo_move_mario_part_from_parent),
						GEO_ASM(0, geo_mario_tilt_torso),
						GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 44, 0, 0, jer_afterimage_Torso_mesh_layer_3),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 125, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_head_rotation),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, jer_afterimage_Head_DL_mesh_layer_3),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 73, -7, 65, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, jer_afterimage_Left_Arm_Color_mesh_layer_3),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, jer_afterimage_Left_Forearm_skinned_mesh_layer_3),
										GEO_ANIMATED_PART(LAYER_TRANSPARENT, 69, 0, 0, jer_afterimage_Left_Forearm_mesh_layer_3),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 73, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(1, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, jer_afterimage_Left_Hand_DL_mesh_layer_3),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 73, -7, -65, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, jer_afterimage_Right_Arm_Color_mesh_layer_3),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, jer_afterimage_Right_Forearm_skinned_mesh_layer_3),
										GEO_ANIMATED_PART(LAYER_TRANSPARENT, 69, 0, 0, jer_afterimage_Right_Forearm_mesh_layer_3),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 73, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(0, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, jer_afterimage_Right_Hand_DL_mesh_layer_3),
												GEO_CLOSE_NODE(),
												GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, -21, -5, 38, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, jer_afterimage_Left_Thigh_Color_mesh_layer_3),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, jer_afterimage_Left_Leg_skinned_mesh_layer_3),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 89, 0, 0, jer_afterimage_Left_Leg_mesh_layer_3),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 97, 0, 0, jer_afterimage_Left_Shoe_mesh_layer_3),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, -21, -5, -38, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, jer_afterimage_Right_Thigh_Color_mesh_layer_3),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, jer_afterimage_Right_Leg_skinned_mesh_layer_3),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 89, 0, 0, jer_afterimage_Right_Leg_mesh_layer_3),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 97, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ASM(2, geo_mario_hand_foot_scaler),
										GEO_SCALE(LAYER_FORCE, 65536),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_TRANSPARENT, jer_afterimage_Right_Shoe_DL_mesh_layer_3),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ASM((LAYER_OPAQUE << 2) | 1, geo_mirror_mario_backface_culling),
		GEO_ASM((LAYER_OPAQUE_DECAL << 2) | 1, geo_mirror_mario_backface_culling),
		GEO_ASM((LAYER_TRANSPARENT << 2) | 1, geo_mirror_mario_backface_culling),
		GEO_ASM((LAYER_TRANSPARENT_DECAL << 2) | 1, geo_mirror_mario_backface_culling),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout jer_afterimage_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SCALE(LAYER_FORCE, 24576),
		GEO_OPEN_NODE(),
			GEO_ASM(0, geo_update_layer_transparency),
			GEO_SWITCH_CASE(2, geo_switch_anim_state),
			GEO_OPEN_NODE(),
				GEO_NODE_START(),
				GEO_OPEN_NODE(),
					GEO_ASM(LAYER_OPAQUE + 3, geo_mario_set_player_colors),
					GEO_ASM(LAYER_OPAQUE_DECAL + 3, geo_mario_set_player_colors),
					GEO_ASM(LAYER_TRANSPARENT + 3, geo_mario_set_player_colors),
					GEO_ASM(LAYER_TRANSPARENT_DECAL + 3, geo_mario_set_player_colors),
					GEO_ASM(LAYER_OPAQUE << 2, geo_mirror_mario_backface_culling),
					GEO_ASM(LAYER_OPAQUE_DECAL << 2, geo_mirror_mario_backface_culling),
					GEO_ASM(LAYER_TRANSPARENT << 2, geo_mirror_mario_backface_culling),
					GEO_ASM(LAYER_TRANSPARENT_DECAL << 2, geo_mirror_mario_backface_culling),
					GEO_SWITCH_CASE(0, geo_switch_mario_stand_run),
					GEO_OPEN_NODE(),
						GEO_NODE_START(),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 53, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE_INTER, 23, 0, 0, jer_afterimage_Butt_mesh_layer_3),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE_INTER, jer_afterimage_Torso_skinned_mesh_layer_3),
									GEO_ASM(0, geo_move_mario_part_from_parent),
									GEO_ASM(0, geo_mario_tilt_torso),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE_INTER, 44, 0, 0, jer_afterimage_Torso_mesh_layer_3),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 125, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(0, geo_mario_head_rotation),
												GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE_INTER, jer_afterimage_Head_DL_mesh_layer_3),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 73, -7, 65, NULL),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE_INTER, 0, 0, 0, jer_afterimage_Left_Arm_Color_mesh_layer_3),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE_INTER, jer_afterimage_Left_Forearm_skinned_mesh_layer_3),
													GEO_ANIMATED_PART(LAYER_OPAQUE_INTER, 69, 0, 0, jer_afterimage_Left_Forearm_mesh_layer_3),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 73, 0, 0, NULL),
														GEO_OPEN_NODE(),
															GEO_ASM(1, geo_mario_hand_foot_scaler),
															GEO_SCALE(LAYER_FORCE, 65536),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_OPAQUE_INTER, jer_afterimage_Left_Hand_DL_mesh_layer_3),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 73, -7, -65, NULL),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE_INTER, 0, 0, 0, jer_afterimage_Right_Arm_Color_mesh_layer_3),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE_INTER, jer_afterimage_Right_Forearm_skinned_mesh_layer_3),
													GEO_ANIMATED_PART(LAYER_OPAQUE_INTER, 69, 0, 0, jer_afterimage_Right_Forearm_mesh_layer_3),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 73, 0, 0, NULL),
														GEO_OPEN_NODE(),
															GEO_ASM(0, geo_mario_hand_foot_scaler),
															GEO_SCALE(LAYER_FORCE, 65536),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_OPAQUE_INTER, jer_afterimage_Right_Hand_DL_mesh_layer_3),
															GEO_CLOSE_NODE(),
															GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, -21, -5, 38, NULL),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE_INTER, 0, 0, 0, jer_afterimage_Left_Thigh_Color_mesh_layer_3),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_OPAQUE_INTER, jer_afterimage_Left_Leg_skinned_mesh_layer_3),
											GEO_ANIMATED_PART(LAYER_OPAQUE_INTER, 89, 0, 0, jer_afterimage_Left_Leg_mesh_layer_3),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE_INTER, 97, 0, 0, jer_afterimage_Left_Shoe_mesh_layer_3),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, -21, -5, -38, NULL),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE_INTER, 0, 0, 0, jer_afterimage_Right_Thigh_Color_mesh_layer_3),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_OPAQUE_INTER, jer_afterimage_Right_Leg_skinned_mesh_layer_3),
											GEO_ANIMATED_PART(LAYER_OPAQUE_INTER, 89, 0, 0, jer_afterimage_Right_Leg_mesh_layer_3),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 97, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(2, geo_mario_hand_foot_scaler),
													GEO_SCALE(LAYER_FORCE, 65536),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_OPAQUE_INTER, jer_afterimage_Right_Shoe_DL_mesh_layer_3),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ASM((LAYER_OPAQUE << 2) | 1, geo_mirror_mario_backface_culling),
					GEO_ASM((LAYER_OPAQUE_DECAL << 2) | 1, geo_mirror_mario_backface_culling),
					GEO_ASM((LAYER_TRANSPARENT << 2) | 1, geo_mirror_mario_backface_culling),
					GEO_ASM((LAYER_TRANSPARENT_DECAL << 2) | 1, geo_mirror_mario_backface_culling),
				GEO_CLOSE_NODE(),
				GEO_BRANCH(1, jer_afterimage_Opacity_Switch_opt1),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE_INTER, jer_afterimage_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, jer_afterimage_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
