extern const GeoLayout jj_cap_jer_nos_6_Cap_Anim_State_Switch_opt1[];
extern const GeoLayout jj_cap_jer_nos_geo[];
extern Lights1 jj_cap_jer_nos_Nos_Label_lights;
extern u8 jj_cap_jer_nos_NosEnvMap_rgba16[];
extern u8 jj_cap_jer_nos_HaloVisor_rgba16[];
extern u8 jj_cap_jer_nos_JerNos_rgba16[];
extern Vtx jj_cap_jer_nos_Wing_Cap_DL_mesh_layer_1_vtx_0[54];
extern Gfx jj_cap_jer_nos_Wing_Cap_DL_mesh_layer_1_tri_0[];
extern Vtx jj_cap_jer_nos_Wing_Cap_DL_mesh_layer_1_vtx_1[18];
extern Gfx jj_cap_jer_nos_Wing_Cap_DL_mesh_layer_1_tri_1[];
extern Vtx jj_cap_jer_nos_Wing_Cap_DL_mesh_layer_4_vtx_0[40];
extern Gfx jj_cap_jer_nos_Wing_Cap_DL_mesh_layer_4_tri_0[];
extern Gfx mat_jj_cap_jer_nos_Nos_Env_Map[];
extern Gfx mat_revert_jj_cap_jer_nos_Nos_Env_Map[];
extern Gfx mat_jj_cap_jer_nos_Visor[];
extern Gfx mat_revert_jj_cap_jer_nos_Visor[];
extern Gfx mat_jj_cap_jer_nos_Nos_Label[];
extern Gfx mat_revert_jj_cap_jer_nos_Nos_Label[];
extern Gfx jj_cap_jer_nos_Wing_Cap_DL_mesh_layer_1[];
extern Gfx jj_cap_jer_nos_Wing_Cap_DL_mesh_layer_4[];
extern Gfx jj_cap_jer_nos_material_revert_render_settings[];
