extern const GeoLayout helmet_lucky_Normal_Cap_State_Switch_opt1[];
extern const GeoLayout helmet_lucky_geo[];
extern Lights1 helmet_lucky_Helmet__CAP__lights;
extern Lights1 helmet_lucky_Visor__GLOVES__lights;
extern Lights1 helmet_lucky_Stripes__EMBLEM__lights;
extern u8 helmet_lucky_king_grey_rgba16[];
extern u8 helmet_lucky_king_grey_shade_rgba16[];
extern Vtx helmet_lucky_Normal_Cap_DL_mesh_layer_1_vtx_0[115];
extern Gfx helmet_lucky_Normal_Cap_DL_mesh_layer_1_tri_0[];
extern Vtx helmet_lucky_Normal_Cap_DL_mesh_layer_1_vtx_1[18];
extern Gfx helmet_lucky_Normal_Cap_DL_mesh_layer_1_tri_1[];
extern Vtx helmet_lucky_Normal_Cap_DL_mesh_layer_1_vtx_2[54];
extern Gfx helmet_lucky_Normal_Cap_DL_mesh_layer_1_tri_2[];
extern Gfx mat_helmet_lucky_Helmet__CAP_[];
extern Gfx mat_helmet_lucky_Visor__GLOVES_[];
extern Gfx mat_revert_helmet_lucky_Visor__GLOVES_[];
extern Gfx mat_helmet_lucky_Stripes__EMBLEM_[];
extern Gfx helmet_lucky_Normal_Cap_DL_mesh_layer_1[];
extern Gfx helmet_lucky_material_revert_render_settings[];
