extern const GeoLayout fludd_nozzle_Wing_Cap_Switch_opt1[];
extern const GeoLayout fludd_nozzle_geo[];
extern Lights1 fludd_nozzle_Yellow_lights;
extern u8 fludd_nozzle_screw_ci8[];
extern u8 fludd_nozzle_screw_pal_rgba16[];
extern u8 fludd_nozzle_steel_i8[];
extern Vtx fludd_nozzle_Wing_Cap_mesh_layer_1_vtx_0[77];
extern Gfx fludd_nozzle_Wing_Cap_mesh_layer_1_tri_0[];
extern Vtx fludd_nozzle_Wing_Cap_mesh_layer_1_vtx_1[51];
extern Gfx fludd_nozzle_Wing_Cap_mesh_layer_1_tri_1[];
extern Gfx mat_fludd_nozzle_Yellow[];
extern Gfx mat_revert_fludd_nozzle_Yellow[];
extern Gfx mat_fludd_nozzle_Steel_001[];
extern Gfx mat_revert_fludd_nozzle_Steel_001[];
extern Gfx fludd_nozzle_Wing_Cap_mesh_layer_1[];
extern Gfx fludd_nozzle_material_revert_render_settings[];
