extern const GeoLayout shades_Normal_Cap_State_Switch_opt1[];
extern const GeoLayout shades_Normal_Cap_State_Switch_opt2[];
extern const GeoLayout shades_Normal_Cap_State_Switch_opt3[];
extern const GeoLayout shades_geo[];
extern Lights1 shades_Sunglasses__EMBLEM__lights;
extern Lights1 shades_Metal__METAL__lights;
extern u8 shades_jer_metal_base_rgba16[];
extern u8 shades_Metal_Shade_rgba16_rgba16[];
extern u8 shades_Metal_Light_rgba16_rgba16[];
extern Vtx shades_Normal_Cap_DL_mesh_layer_1_vtx_0[62];
extern Gfx shades_Normal_Cap_DL_mesh_layer_1_tri_0[];
extern Vtx shades_Normal_Cap_DL_mesh_layer_1_vtx_1[42];
extern Gfx shades_Normal_Cap_DL_mesh_layer_1_tri_1[];
extern Gfx mat_shades_Sunglasses_reflection[];
extern Gfx mat_revert_shades_Sunglasses_reflection[];
extern Gfx mat_shades_Sunglasses__EMBLEM_[];
extern Gfx mat_shades_Metal__METAL_[];
extern Gfx mat_revert_shades_Metal__METAL_[];
extern Gfx shades_Normal_Cap_DL_mesh_layer_1[];
extern Gfx shades_Normal_Cap_DL_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx shades_material_revert_render_settings[];
