extern const GeoLayout davy_wing_cap_Wing_Cap_Switch_opt1[];
extern const GeoLayout davy_wing_cap_Wing_Cap_Switch_opt2[];
extern const GeoLayout davy_wing_cap_Wing_Cap_Switch_opt3[];
extern const GeoLayout davy_wing_cap_geo[];
extern Lights1 davy_wing_cap_Davy_Cap__CAP__lights;
extern Lights1 davy_wing_cap_Davy_Cap_Bottom__CAP__lights;
extern Lights1 davy_wing_cap_Davy_Logo__CAP__lights;
extern Lights1 davy_wing_cap_Davy_Emblem__EMBLEM__lights;
extern Lights1 davy_wing_cap_Metal__METAL__lights;
extern u8 davy_wing_cap_quin_shade_ia8[];
extern u8 davy_wing_cap_cap_logo_rgba16[];
extern u8 davy_wing_cap_davy_letter_rgba16[];
extern u8 davy_wing_cap_Metal_Shade_rgba16_rgba16[];
extern u8 davy_wing_cap_Metal_Light_rgba16_rgba16[];
extern u8 davy_wing_cap_wing_2_ia8[];
extern u8 davy_wing_cap_wing1_ia8[];
extern Vtx davy_wing_cap_Wing_Cap_mesh_layer_1_vtx_0[44];
extern Gfx davy_wing_cap_Wing_Cap_mesh_layer_1_tri_0[];
extern Vtx davy_wing_cap_Wing_Cap_mesh_layer_1_vtx_1[11];
extern Gfx davy_wing_cap_Wing_Cap_mesh_layer_1_tri_1[];
extern Vtx davy_wing_cap_Wing_Cap_mesh_layer_1_vtx_2[6];
extern Gfx davy_wing_cap_Wing_Cap_mesh_layer_1_tri_2[];
extern Vtx davy_wing_cap_Wing_Cap_mesh_layer_1_vtx_3[6];
extern Gfx davy_wing_cap_Wing_Cap_mesh_layer_1_tri_3[];
extern Vtx davy_wing_cap_Wings_mesh_layer_4_vtx_0[8];
extern Gfx davy_wing_cap_Wings_mesh_layer_4_tri_0[];
extern Vtx davy_wing_cap_Wings_mesh_layer_4_vtx_1[8];
extern Gfx davy_wing_cap_Wings_mesh_layer_4_tri_1[];
extern Gfx mat_davy_wing_cap_Davy_Cap__CAP_[];
extern Gfx mat_davy_wing_cap_Davy_Cap_Bottom__CAP_[];
extern Gfx mat_davy_wing_cap_Davy_Logo__CAP_[];
extern Gfx mat_davy_wing_cap_Davy_Emblem__EMBLEM_[];
extern Gfx mat_davy_wing_cap_Metal__METAL_[];
extern Gfx mat_revert_davy_wing_cap_Metal__METAL_[];
extern Gfx mat_davy_wing_cap_Wing_Tip[];
extern Gfx mat_revert_davy_wing_cap_Wing_Tip[];
extern Gfx mat_davy_wing_cap_Wing_Base[];
extern Gfx mat_revert_davy_wing_cap_Wing_Base[];
extern Gfx davy_wing_cap_Wing_Cap_mesh_layer_1[];
extern Gfx davy_wing_cap_Wing_Cap_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx davy_wing_cap_Wings_mesh_layer_4[];
extern Gfx davy_wing_cap_Wings_mesh_layer_4_mat_override_Metal__METAL__0[];
extern Gfx davy_wing_cap_material_revert_render_settings[];
