extern const GeoLayout dynamite_geo[];
extern Lights1 dynamite_Dynamite_lights;
extern Lights1 dynamite_Bob_omb_Fuse_lights;
extern Vtx dynamite_006_offset_mesh_layer_1_vtx_0[37];
extern Gfx dynamite_006_offset_mesh_layer_1_tri_0[];
extern Vtx dynamite_006_offset_mesh_layer_1_vtx_1[12];
extern Gfx dynamite_006_offset_mesh_layer_1_tri_1[];
extern Gfx mat_dynamite_Dynamite[];
extern Gfx mat_dynamite_Bob_omb_Fuse[];
extern Gfx dynamite_006_offset_mesh_layer_1[];
