extern const GeoLayout screw_Metal_Cap_State_Switch_opt1[];
extern const GeoLayout screw_geo[];
extern Lights1 screw_Screw_lights;
extern u8 screw_davy_metal_base_rgba16[];
extern u8 screw_davy_metal_shine_rgba16[];
extern Vtx screw_Metal_Cap_DL_mesh_layer_1_vtx_0[315];
extern Gfx screw_Metal_Cap_DL_mesh_layer_1_tri_0[];
extern Gfx mat_screw_Screw[];
extern Gfx mat_revert_screw_Screw[];
extern Gfx screw_Metal_Cap_DL_mesh_layer_1[];
extern Gfx screw_material_revert_render_settings[];
