extern const GeoLayout screw_Metal_Cap_State_Switch_opt1[];
extern const GeoLayout screw_Metal_Cap_State_Switch_opt2[];
extern const GeoLayout screw_Metal_Cap_State_Switch_opt3[];
extern const GeoLayout screw_geo[];
extern Lights1 screw_Screw_lights;
extern Lights1 screw_Jer_Metal_METAL_lights;
extern u8 screw_silver_rgba16[];
extern u8 screw_metal_bones_shade_rgba16[];
extern u8 screw_custom_mario_metal_base_rgba16_i8[];
extern u8 screw_custom_mario_metal_shine_rgba16_i8[];
extern Vtx screw_Metal_Cap_DL_mesh_layer_1_vtx_0[315];
extern Gfx screw_Metal_Cap_DL_mesh_layer_1_tri_0[];
extern Gfx mat_screw_Screw[];
extern Gfx mat_revert_screw_Screw[];
extern Gfx mat_screw_Jer_Metal_METAL[];
extern Gfx mat_revert_screw_Jer_Metal_METAL[];
extern Gfx screw_Metal_Cap_DL_mesh_layer_1[];
extern Gfx screw_Metal_Cap_DL_mesh_layer_1_mat_override_Jer_Metal_METAL_0[];
extern Gfx screw_material_revert_render_settings[];
