extern const GeoLayout lucky_Left_Hand_Open[];
extern const GeoLayout lucky_Right_Hand_Open[];
extern const GeoLayout lucky_Right_Hand_Peace[];
extern const GeoLayout lucky_7_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_lucky_Left_Hand_Open[];
extern const GeoLayout lucky_7_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_lucky_Right_Hand_Open[];
extern const GeoLayout lucky_7_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_lucky_Right_Hand_Peace[];
extern const GeoLayout lucky_7_LoD_Switch_opt0_Cap_State_Switch_opt1[];
extern const GeoLayout lucky_7_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_lucky_Left_Hand_Open[];
extern const GeoLayout lucky_7_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_lucky_Right_Hand_Open[];
extern const GeoLayout lucky_7_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_lucky_Right_Hand_Peace[];
extern const GeoLayout lucky_7_LoD_Switch_opt0_Cap_State_Switch_opt2[];
extern const GeoLayout lucky_7_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_lucky_Left_Hand_Open[];
extern const GeoLayout lucky_7_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_lucky_Right_Hand_Open[];
extern const GeoLayout lucky_7_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_lucky_Right_Hand_Peace[];
extern const GeoLayout lucky_7_LoD_Switch_opt0_Cap_State_Switch_opt3[];
extern const GeoLayout lucky_geo[];
extern Lights1 lucky_Pants__PANTS__lights;
extern Lights1 lucky_Gloves__GLOVES__lights;
extern Lights1 lucky_Jacket__SHIRT__lights;
extern Lights1 lucky_Jacket_Front__SHIRT__lights;
extern Lights1 lucky_Visor__CAP__lights;
extern Lights1 lucky_Stripes__HAIR__lights;
extern Lights1 lucky_Metal__METAL__lights;
extern Lights1 lucky_Helmet__SKIN__lights;
extern Lights1 lucky_NOS_Tank_lights;
extern Lights1 lucky_Spoiler_lights;
extern Lights1 lucky_Spoiler_Voltex_lights;
extern Lights1 lucky_Spoiler_Post_lights;
extern Lights1 lucky_Armband__EMBLEM__lights;
extern Lights1 lucky_Boots__SHOES__lights;
extern u8 lucky_jacket_rgba16[];
extern u8 lucky_king_gold_rgba16[];
extern u8 lucky_king_gold_shade_rgba16[];
extern u8 lucky_jer_metal_base_rgba16[];
extern u8 lucky_jer_metal_shine_rgba16[];
extern u8 lucky_jer_tank_rgba16[];
extern u8 lucky_stainless_steel_rgba16[];
extern u8 lucky_voltex_rgba16[];
extern u8 lucky_spoiler_posts_rgba16[];
extern Vtx lucky_Torso_mesh_layer_1_vtx_0[17];
extern Gfx lucky_Torso_mesh_layer_1_tri_0[];
extern Vtx lucky_Torso_mesh_layer_1_vtx_1[26];
extern Gfx lucky_Torso_mesh_layer_1_tri_1[];
extern Vtx lucky_Torso_mesh_layer_1_vtx_2[69];
extern Gfx lucky_Torso_mesh_layer_1_tri_2[];
extern Vtx lucky_Torso_mesh_layer_1_vtx_3[20];
extern Gfx lucky_Torso_mesh_layer_1_tri_3[];
extern Vtx lucky_Torso_mesh_layer_1_vtx_4[8];
extern Gfx lucky_Torso_mesh_layer_1_tri_4[];
extern Vtx lucky_Torso_mesh_layer_1_vtx_5[22];
extern Gfx lucky_Torso_mesh_layer_1_tri_5[];
extern Vtx lucky_Head_DL_mesh_layer_1_vtx_0[116];
extern Gfx lucky_Head_DL_mesh_layer_1_tri_0[];
extern Vtx lucky_Head_DL_mesh_layer_1_vtx_1[54];
extern Gfx lucky_Head_DL_mesh_layer_1_tri_1[];
extern Vtx lucky_Head_DL_mesh_layer_1_vtx_2[18];
extern Gfx lucky_Head_DL_mesh_layer_1_tri_2[];
extern Vtx lucky_Left_Arm_Color_mesh_layer_1_vtx_0[20];
extern Gfx lucky_Left_Arm_Color_mesh_layer_1_tri_0[];
extern Vtx lucky_Left_Forearm_mesh_layer_1_vtx_0[16];
extern Gfx lucky_Left_Forearm_mesh_layer_1_tri_0[];
extern Vtx lucky_Left_Hand_DL_mesh_layer_1_vtx_0[25];
extern Gfx lucky_Left_Hand_DL_mesh_layer_1_tri_0[];
extern Vtx lucky_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1_vtx_0[40];
extern Gfx lucky_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1_tri_0[];
extern Vtx lucky_Nos_Tank_DL_mesh_layer_1_vtx_0[76];
extern Gfx lucky_Nos_Tank_DL_mesh_layer_1_tri_0[];
extern Vtx lucky_Nos_Tank_DL_mesh_layer_1_vtx_1[18];
extern Gfx lucky_Nos_Tank_DL_mesh_layer_1_tri_1[];
extern Vtx lucky_Nos_Tank_DL_mesh_layer_1_vtx_2[48];
extern Gfx lucky_Nos_Tank_DL_mesh_layer_1_tri_2[];
extern Vtx lucky_Nos_Tank_DL_mesh_layer_1_vtx_3[22];
extern Gfx lucky_Nos_Tank_DL_mesh_layer_1_tri_3[];
extern Vtx lucky_Nos_Tank_DL_mesh_layer_4_vtx_0[8];
extern Gfx lucky_Nos_Tank_DL_mesh_layer_4_tri_0[];
extern Vtx lucky_Right_Arm_Color_mesh_layer_1_vtx_0[30];
extern Gfx lucky_Right_Arm_Color_mesh_layer_1_tri_0[];
extern Vtx lucky_Right_Arm_Color_mesh_layer_1_vtx_1[25];
extern Gfx lucky_Right_Arm_Color_mesh_layer_1_tri_1[];
extern Vtx lucky_Right_Forearm_mesh_layer_1_vtx_0[16];
extern Gfx lucky_Right_Forearm_mesh_layer_1_tri_0[];
extern Vtx lucky_Right_Hand_DL_mesh_layer_1_vtx_0[25];
extern Gfx lucky_Right_Hand_DL_mesh_layer_1_tri_0[];
extern Vtx lucky_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1_vtx_0[41];
extern Gfx lucky_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1_tri_0[];
extern Vtx lucky_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1_vtx_0[49];
extern Gfx lucky_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1_tri_0[];
extern Vtx lucky_Left_Thigh_Color_mesh_layer_1_vtx_0[17];
extern Gfx lucky_Left_Thigh_Color_mesh_layer_1_tri_0[];
extern Vtx lucky_Left_Leg_mesh_layer_1_vtx_0[12];
extern Gfx lucky_Left_Leg_mesh_layer_1_tri_0[];
extern Vtx lucky_Left_Leg_mesh_layer_1_vtx_1[13];
extern Gfx lucky_Left_Leg_mesh_layer_1_tri_1[];
extern Vtx lucky_Left_Shoe_mesh_layer_1_vtx_0[23];
extern Gfx lucky_Left_Shoe_mesh_layer_1_tri_0[];
extern Vtx lucky_Right_Thigh_Color_mesh_layer_1_vtx_0[17];
extern Gfx lucky_Right_Thigh_Color_mesh_layer_1_tri_0[];
extern Vtx lucky_Right_Leg_mesh_layer_1_vtx_0[12];
extern Gfx lucky_Right_Leg_mesh_layer_1_tri_0[];
extern Vtx lucky_Right_Leg_mesh_layer_1_vtx_1[13];
extern Gfx lucky_Right_Leg_mesh_layer_1_tri_1[];
extern Vtx lucky_Right_Shoe_DL_mesh_layer_1_vtx_0[23];
extern Gfx lucky_Right_Shoe_DL_mesh_layer_1_tri_0[];
extern Gfx mat_lucky_Pants__PANTS_[];
extern Gfx mat_lucky_Gloves__GLOVES_[];
extern Gfx mat_lucky_Jacket__SHIRT_[];
extern Gfx mat_lucky_Jacket_Front__SHIRT_[];
extern Gfx mat_lucky_Visor__CAP_[];
extern Gfx mat_revert_lucky_Visor__CAP_[];
extern Gfx mat_lucky_Stripes__HAIR_[];
extern Gfx mat_lucky_Metal__METAL_[];
extern Gfx mat_revert_lucky_Metal__METAL_[];
extern Gfx mat_lucky_Helmet__SKIN_[];
extern Gfx mat_lucky_NOS_Tank[];
extern Gfx mat_lucky_Steel[];
extern Gfx mat_revert_lucky_Steel[];
extern Gfx mat_lucky_Spoiler[];
extern Gfx mat_lucky_Spoiler_Voltex[];
extern Gfx mat_lucky_Spoiler_Post[];
extern Gfx mat_revert_lucky_Spoiler_Post[];
extern Gfx mat_lucky_Armband__EMBLEM_[];
extern Gfx mat_lucky_Boots__SHOES_[];
extern Gfx lucky_Torso_mesh_layer_1[];
extern Gfx lucky_Torso_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx lucky_Head_DL_mesh_layer_1[];
extern Gfx lucky_Head_DL_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx lucky_Left_Arm_Color_mesh_layer_1[];
extern Gfx lucky_Left_Arm_Color_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx lucky_Left_Forearm_mesh_layer_1[];
extern Gfx lucky_Left_Forearm_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx lucky_Left_Hand_DL_mesh_layer_1[];
extern Gfx lucky_Left_Hand_DL_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx lucky_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1[];
extern Gfx lucky_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx lucky_Nos_Tank_DL_mesh_layer_1[];
extern Gfx lucky_Nos_Tank_DL_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx lucky_Nos_Tank_DL_mesh_layer_4[];
extern Gfx lucky_Nos_Tank_DL_mesh_layer_4_mat_override_Metal__METAL__0[];
extern Gfx lucky_Right_Arm_Color_mesh_layer_1[];
extern Gfx lucky_Right_Arm_Color_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx lucky_Right_Forearm_mesh_layer_1[];
extern Gfx lucky_Right_Forearm_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx lucky_Right_Hand_DL_mesh_layer_1[];
extern Gfx lucky_Right_Hand_DL_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx lucky_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1[];
extern Gfx lucky_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx lucky_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1[];
extern Gfx lucky_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx lucky_Left_Thigh_Color_mesh_layer_1[];
extern Gfx lucky_Left_Thigh_Color_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx lucky_Left_Leg_mesh_layer_1[];
extern Gfx lucky_Left_Leg_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx lucky_Left_Shoe_mesh_layer_1[];
extern Gfx lucky_Left_Shoe_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx lucky_Right_Thigh_Color_mesh_layer_1[];
extern Gfx lucky_Right_Thigh_Color_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx lucky_Right_Leg_mesh_layer_1[];
extern Gfx lucky_Right_Leg_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx lucky_Right_Shoe_DL_mesh_layer_1[];
extern Gfx lucky_Right_Shoe_DL_mesh_layer_1_mat_override_Metal__METAL__0[];
