extern const GeoLayout jj_cap_jess_ice_6_Cap_Anim_State_Switch_opt1[];
extern const GeoLayout jj_cap_jess_ice_geo[];
extern Lights1 jj_cap_jess_ice_Metal_Flower_Stem_lights;
extern Lights1 jj_cap_jess_ice_Metal_Flower_Leaf_lights;
extern u8 jj_cap_jess_ice_JessIce_rgba16[];
extern u8 jj_cap_jess_ice_FlowerEyesIce_ia8[];
extern u8 jj_cap_jess_ice_FlowerLeaves_ia8[];
extern Vtx jj_cap_jess_ice_Metal_Cap_DL_mesh_layer_1_vtx_0[23];
extern Gfx jj_cap_jess_ice_Metal_Cap_DL_mesh_layer_1_tri_0[];
extern Vtx jj_cap_jess_ice_Metal_Cap_DL_mesh_layer_7_vtx_0[45];
extern Gfx jj_cap_jess_ice_Metal_Cap_DL_mesh_layer_7_tri_0[];
extern Vtx jj_cap_jess_ice_Metal_Cap_DL_mesh_layer_4_vtx_0[6];
extern Gfx jj_cap_jess_ice_Metal_Cap_DL_mesh_layer_4_tri_0[];
extern Vtx jj_cap_jess_ice_Metal_Cap_DL_mesh_layer_4_vtx_1[15];
extern Gfx jj_cap_jess_ice_Metal_Cap_DL_mesh_layer_4_tri_1[];
extern Gfx mat_jj_cap_jess_ice_Metal_Flower_Stem[];
extern Gfx mat_jj_cap_jess_ice_Ice[];
extern Gfx mat_revert_jj_cap_jess_ice_Ice[];
extern Gfx mat_jj_cap_jess_ice_Metal_Flower_Eyes_Texture[];
extern Gfx mat_revert_jj_cap_jess_ice_Metal_Flower_Eyes_Texture[];
extern Gfx mat_jj_cap_jess_ice_Metal_Flower_Leaf[];
extern Gfx mat_revert_jj_cap_jess_ice_Metal_Flower_Leaf[];
extern Gfx jj_cap_jess_ice_Metal_Cap_DL_mesh_layer_1[];
extern Gfx jj_cap_jess_ice_Metal_Cap_DL_mesh_layer_7[];
extern Gfx jj_cap_jess_ice_Metal_Cap_DL_mesh_layer_4[];
extern Gfx jj_cap_jess_ice_material_revert_render_settings[];
