extern const GeoLayout helmet_Normal_Cap_State_Switch_opt1[];
extern const GeoLayout helmet_geo[];
extern Lights1 helmet_Helmet__CAP__lights;
extern Lights1 helmet_Visor_lights;
extern Lights1 helmet_Visor_texture_lights;
extern Lights1 helmet_Stripes__EMBLEM__lights;
extern u8 helmet_visor_rgba16[];
extern Vtx helmet_Normal_Cap_DL_mesh_layer_1_vtx_0[115];
extern Gfx helmet_Normal_Cap_DL_mesh_layer_1_tri_0[];
extern Vtx helmet_Normal_Cap_DL_mesh_layer_1_vtx_1[8];
extern Gfx helmet_Normal_Cap_DL_mesh_layer_1_tri_1[];
extern Vtx helmet_Normal_Cap_DL_mesh_layer_1_vtx_2[10];
extern Gfx helmet_Normal_Cap_DL_mesh_layer_1_tri_2[];
extern Vtx helmet_Normal_Cap_DL_mesh_layer_1_vtx_3[54];
extern Gfx helmet_Normal_Cap_DL_mesh_layer_1_tri_3[];
extern Gfx mat_helmet_Helmet__CAP_[];
extern Gfx mat_helmet_Visor[];
extern Gfx mat_helmet_Visor_texture[];
extern Gfx mat_helmet_Stripes__EMBLEM_[];
extern Gfx helmet_Normal_Cap_DL_mesh_layer_1[];
extern Gfx helmet_material_revert_render_settings[];
