extern const GeoLayout miner_cap_Normal_Cap_State_Switch_opt1[];
extern const GeoLayout miner_cap_geo[];
extern Lights1 miner_cap_Jessilynn_Cap_Bottom__CAP__lights;
extern Lights1 miner_cap_Jessilynn_Cap__CAP__lights;
extern Lights1 miner_cap_Jessilynn_Hair__HAIR__lights;
extern Lights1 miner_cap_Jessilynn_Headlamp__HAIR__lights;
extern u8 miner_cap_jess_shade_ia8[];
extern u8 miner_cap_jess_headlamp_rgba16[];
extern Vtx miner_cap_Normal_Cap_DL_mesh_layer_1_vtx_0[9];
extern Gfx miner_cap_Normal_Cap_DL_mesh_layer_1_tri_0[];
extern Vtx miner_cap_Normal_Cap_DL_mesh_layer_1_vtx_1[57];
extern Gfx miner_cap_Normal_Cap_DL_mesh_layer_1_tri_1[];
extern Vtx miner_cap_Normal_Cap_DL_mesh_layer_1_vtx_2[17];
extern Gfx miner_cap_Normal_Cap_DL_mesh_layer_1_tri_2[];
extern Vtx miner_cap_Normal_Cap_DL_mesh_layer_1_vtx_3[7];
extern Gfx miner_cap_Normal_Cap_DL_mesh_layer_1_tri_3[];
extern Gfx mat_miner_cap_Jessilynn_Cap_Bottom__CAP_[];
extern Gfx mat_miner_cap_Jessilynn_Cap__CAP_[];
extern Gfx mat_miner_cap_Jessilynn_Hair__HAIR_[];
extern Gfx mat_miner_cap_Jessilynn_Headlamp__HAIR_[];
extern Gfx miner_cap_Normal_Cap_DL_mesh_layer_1[];
extern Gfx miner_cap_material_revert_render_settings[];
