extern const GeoLayout jj_cap_jer_metal_6_Cap_Anim_State_Switch_opt1[];
extern const GeoLayout jj_cap_jer_metal_geo[];
extern Lights1 jj_cap_jer_metal_Metal_Flower_Stem_lights;
extern Lights1 jj_cap_jer_metal_Metal_Flower_Leaf_lights;
extern u8 jj_cap_jer_metal_JerMetal_rgba16[];
extern u8 jj_cap_jer_metal_FlowerEyesMetal_ia8[];
extern u8 jj_cap_jer_metal_FlowerLeaves_ia8[];
extern Vtx jj_cap_jer_metal_Metal_Cap_DL_mesh_layer_1_vtx_0[23];
extern Gfx jj_cap_jer_metal_Metal_Cap_DL_mesh_layer_1_tri_0[];
extern Vtx jj_cap_jer_metal_Metal_Cap_DL_mesh_layer_1_vtx_1[108];
extern Gfx jj_cap_jer_metal_Metal_Cap_DL_mesh_layer_1_tri_1[];
extern Vtx jj_cap_jer_metal_Metal_Cap_DL_mesh_layer_4_vtx_0[6];
extern Gfx jj_cap_jer_metal_Metal_Cap_DL_mesh_layer_4_tri_0[];
extern Vtx jj_cap_jer_metal_Metal_Cap_DL_mesh_layer_4_vtx_1[15];
extern Gfx jj_cap_jer_metal_Metal_Cap_DL_mesh_layer_4_tri_1[];
extern Gfx mat_jj_cap_jer_metal_Metal_Flower_Stem[];
extern Gfx mat_jj_cap_jer_metal_Metal[];
extern Gfx mat_revert_jj_cap_jer_metal_Metal[];
extern Gfx mat_jj_cap_jer_metal_Metal_Flower_Eyes_Texture[];
extern Gfx mat_revert_jj_cap_jer_metal_Metal_Flower_Eyes_Texture[];
extern Gfx mat_jj_cap_jer_metal_Metal_Flower_Leaf[];
extern Gfx mat_revert_jj_cap_jer_metal_Metal_Flower_Leaf[];
extern Gfx jj_cap_jer_metal_Metal_Cap_DL_mesh_layer_1[];
extern Gfx jj_cap_jer_metal_Metal_Cap_DL_mesh_layer_4[];
extern Gfx jj_cap_jer_metal_material_revert_render_settings[];
