#include "src/game/envfx_snow.h"

const GeoLayout davy_Capless_Head[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 155, 0, 0, 0, 0, 0),
	GEO_OPEN_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout davy_Left_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 120, 0, 0, davy_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout davy_Right_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 120, 0, 0, davy_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout davy_Right_Hand_Peace[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 120, 0, 0, davy_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout davy_Right_Hand_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 120, 0, 0, davy_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, davy_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout davy_Right_Hand_Wing_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 120, 0, 0, davy_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, davy_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout davy_Magma_Davy_Switch_Option_Magma_Left_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 120, 0, 0, davy_Magma_Davy_Switch_Option_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout davy_Magma_Davy_Switch_Option_Magma_Right_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 120, 0, 0, davy_Magma_Davy_Switch_Option_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout davy_Magma_Davy_Switch_Option_Magma_Right_Hand_Peace[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 120, 0, 0, davy_Magma_Davy_Switch_Option_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout davy_Magma_Davy_Switch_Option_Magma_Right_Hand_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 120, 0, 0, davy_Magma_Davy_Switch_Option_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, davy_Magma_Davy_Switch_Option_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout davy_Magma_Davy_Switch_Option_Magma_Right_Hand_Wing_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 120, 0, 0, davy_Magma_Davy_Switch_Option_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, davy_Magma_Davy_Switch_Option_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout davy_B_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_davy_Capless_Head[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 155, 0, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout davy_B_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_davy_Magma_Davy_Switch_Option_Magma_Left_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 120, 0, 0, davy_Magma_Davy_Switch_Option_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout davy_B_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_davy_Magma_Davy_Switch_Option_Magma_Right_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 120, 0, 0, davy_Magma_Davy_Switch_Option_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout davy_B_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_davy_Magma_Davy_Switch_Option_Magma_Right_Hand_Peace[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 120, 0, 0, davy_Magma_Davy_Switch_Option_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout davy_B_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_davy_Magma_Davy_Switch_Option_Magma_Right_Hand_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 120, 0, 0, davy_Magma_Davy_Switch_Option_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, davy_Magma_Davy_Switch_Option_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout davy_B_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_davy_Magma_Davy_Switch_Option_Magma_Right_Hand_Wing_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 120, 0, 0, davy_Magma_Davy_Switch_Option_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, davy_Magma_Davy_Switch_Option_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout davy_B_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 29981),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_TRANSPARENT, 34, 0, 0, davy_Magma_Davy_Switch_Option_Butt_mesh_layer_1),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_TRANSPARENT, davy_Magma_Davy_Switch_Option_Torso_skinned_mesh_layer_1),
					GEO_ASM(0, geo_move_mario_part_from_parent),
					GEO_ASM(0, geo_mario_tilt_torso),
					GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 66, 0, 0, davy_Magma_Davy_Switch_Option_Torso_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
							GEO_OPEN_NODE(),
								GEO_NODE_START(),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, davy_Magma_Davy_Switch_Option_Scarf_DL_mesh_layer_1),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, davy_Magma_Davy_Switch_Option_Scarf_DL_mesh_layer_4),
								GEO_CLOSE_NODE(),
								GEO_BRANCH(1, davy_B_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_davy_Capless_Head),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 155, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(0, geo_mario_head_rotation),
								GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_TRANSPARENT, davy_Magma_Davy_Switch_Option_Head_DL_mesh_layer_1),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 110, -10, 99, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, davy_Magma_Davy_Switch_Option_Left_Arm_Color_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, davy_Magma_Davy_Switch_Option_Left_Forearm_skinned_mesh_layer_1),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 115, 0, 0, davy_Magma_Davy_Switch_Option_Left_Forearm_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(1, geo_switch_mario_hand),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 120, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(1, geo_mario_hand_foot_scaler),
													GEO_SCALE(LAYER_FORCE, 65536),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_TRANSPARENT, davy_Magma_Davy_Switch_Option_Left_Hand_DL_mesh_layer_1),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, davy_B_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_davy_Magma_Davy_Switch_Option_Magma_Left_Hand_Open),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 110, -10, -99, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, davy_Magma_Davy_Switch_Option_Right_Arm_Color_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, davy_Magma_Davy_Switch_Option_Right_Forearm_skinned_mesh_layer_1),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 115, 0, 0, davy_Magma_Davy_Switch_Option_Right_Forearm_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_hand),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 120, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(0, geo_mario_hand_foot_scaler),
													GEO_SCALE(LAYER_FORCE, 65536),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_TRANSPARENT, davy_Magma_Davy_Switch_Option_Right_Hand_DL_mesh_layer_1),
													GEO_CLOSE_NODE(),
													GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, davy_B_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_davy_Magma_Davy_Switch_Option_Magma_Right_Hand_Open),
											GEO_BRANCH(1, davy_B_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_davy_Magma_Davy_Switch_Option_Magma_Right_Hand_Peace),
											GEO_BRANCH(1, davy_B_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_davy_Magma_Davy_Switch_Option_Magma_Right_Hand_Cap),
											GEO_BRANCH(1, davy_B_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1_jump_davy_Magma_Davy_Switch_Option_Magma_Right_Hand_Wing_Cap),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, -31, 7, 57, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, davy_Magma_Davy_Switch_Option_Left_Thigh_Color_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 189, 0, 0, davy_Magma_Davy_Switch_Option_Left_Leg_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 152, 0, 0, davy_Magma_Davy_Switch_Option_Left_Shoe_mesh_layer_1),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, -31, 7, -57, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, davy_Magma_Davy_Switch_Option_Right_Thigh_Color_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 189, 0, 0, davy_Magma_Davy_Switch_Option_Right_Leg_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 152, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ASM(2, geo_mario_hand_foot_scaler),
									GEO_SCALE(LAYER_FORCE, 65536),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, davy_Magma_Davy_Switch_Option_Right_Shoe_DL_mesh_layer_1),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout davy_Magma_Davy[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 3, 0, 0, 0, 0),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_cap_effect),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_SCALE(LAYER_FORCE, 29981),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 34, 0, 0, davy_Magma_Davy_Switch_Option_Butt_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, davy_Magma_Davy_Switch_Option_Torso_skinned_mesh_layer_1),
							GEO_ASM(0, geo_move_mario_part_from_parent),
							GEO_ASM(0, geo_mario_tilt_torso),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 66, 0, 0, davy_Magma_Davy_Switch_Option_Torso_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, davy_Magma_Davy_Switch_Option_Scarf_DL_mesh_layer_1),
											GEO_DISPLAY_LIST(LAYER_ALPHA, davy_Magma_Davy_Switch_Option_Scarf_DL_mesh_layer_4),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, davy_Capless_Head),
									GEO_CLOSE_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 155, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ASM(0, geo_mario_head_rotation),
										GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, davy_Magma_Davy_Switch_Option_Head_DL_mesh_layer_1),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 110, -10, 99, NULL),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, davy_Magma_Davy_Switch_Option_Left_Arm_Color_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, davy_Magma_Davy_Switch_Option_Left_Forearm_skinned_mesh_layer_1),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 115, 0, 0, davy_Magma_Davy_Switch_Option_Left_Forearm_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_SWITCH_CASE(1, geo_switch_mario_hand),
												GEO_OPEN_NODE(),
													GEO_NODE_START(),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 120, 0, 0, NULL),
														GEO_OPEN_NODE(),
															GEO_ASM(1, geo_mario_hand_foot_scaler),
															GEO_SCALE(LAYER_FORCE, 65536),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_OPAQUE, davy_Magma_Davy_Switch_Option_Left_Hand_DL_mesh_layer_1),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
													GEO_BRANCH(1, davy_Magma_Davy_Switch_Option_Magma_Left_Hand_Open),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 110, -10, -99, NULL),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, davy_Magma_Davy_Switch_Option_Right_Arm_Color_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, davy_Magma_Davy_Switch_Option_Right_Forearm_skinned_mesh_layer_1),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 115, 0, 0, davy_Magma_Davy_Switch_Option_Right_Forearm_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_SWITCH_CASE(0, geo_switch_mario_hand),
												GEO_OPEN_NODE(),
													GEO_NODE_START(),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 120, 0, 0, NULL),
														GEO_OPEN_NODE(),
															GEO_ASM(0, geo_mario_hand_foot_scaler),
															GEO_SCALE(LAYER_FORCE, 65536),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_OPAQUE, davy_Magma_Davy_Switch_Option_Right_Hand_DL_mesh_layer_1),
															GEO_CLOSE_NODE(),
															GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
													GEO_BRANCH(1, davy_Magma_Davy_Switch_Option_Magma_Right_Hand_Open),
													GEO_BRANCH(1, davy_Magma_Davy_Switch_Option_Magma_Right_Hand_Peace),
													GEO_BRANCH(1, davy_Magma_Davy_Switch_Option_Magma_Right_Hand_Cap),
													GEO_BRANCH(1, davy_Magma_Davy_Switch_Option_Magma_Right_Hand_Wing_Cap),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, -31, 7, 57, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, davy_Magma_Davy_Switch_Option_Left_Thigh_Color_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 189, 0, 0, davy_Magma_Davy_Switch_Option_Left_Leg_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 152, 0, 0, davy_Magma_Davy_Switch_Option_Left_Shoe_mesh_layer_1),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, -31, 7, -57, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, davy_Magma_Davy_Switch_Option_Right_Thigh_Color_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 189, 0, 0, davy_Magma_Davy_Switch_Option_Right_Leg_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 152, 0, 0, NULL),
										GEO_OPEN_NODE(),
											GEO_ASM(2, geo_mario_hand_foot_scaler),
											GEO_SCALE(LAYER_FORCE, 65536),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_OPAQUE, davy_Magma_Davy_Switch_Option_Right_Shoe_DL_mesh_layer_1),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, davy_B_LoD_Switch_opt0_Cap_State_Switch_opt2_Cap_State_Switch_opt1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout davy_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_davy_Capless_Head[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 155, 0, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout davy_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_davy_Left_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 120, 0, 0, davy_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout davy_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_davy_Right_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 120, 0, 0, davy_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout davy_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_davy_Right_Hand_Peace[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 120, 0, 0, davy_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout davy_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_davy_Right_Hand_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 120, 0, 0, davy_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, davy_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout davy_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_davy_Right_Hand_Wing_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 120, 0, 0, davy_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, davy_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout davy_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Eye_State_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, davy_Head_DL_mesh_layer_1_mat_override_Davy_Eyes_Half_0),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, davy_Head_DL_mesh_layer_5_mat_override_Davy_Eyes_Half_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout davy_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Eye_State_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, davy_Head_DL_mesh_layer_1_mat_override_Davy_Eyes_Closed_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, davy_Head_DL_mesh_layer_5_mat_override_Davy_Eyes_Closed_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout davy_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Eye_State_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, davy_Head_DL_mesh_layer_1_mat_override_Davy_Eyes_Left_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, davy_Head_DL_mesh_layer_5_mat_override_Davy_Eyes_Left_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout davy_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Eye_State_Switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, davy_Head_DL_mesh_layer_1_mat_override_Davy_Eyes_Right_3),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, davy_Head_DL_mesh_layer_5_mat_override_Davy_Eyes_Right_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout davy_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Eye_State_Switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, davy_Head_DL_mesh_layer_1_mat_override_Davy_Eyes_Up_4),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, davy_Head_DL_mesh_layer_5_mat_override_Davy_Eyes_Up_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout davy_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Eye_State_Switch_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, davy_Head_DL_mesh_layer_1_mat_override_Davy_Eyes_Down_5),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, davy_Head_DL_mesh_layer_5_mat_override_Davy_Eyes_Down_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout davy_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Eye_State_Switch_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, davy_Head_DL_mesh_layer_1_mat_override_Davy_Eyes_Dead_6),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, davy_Head_DL_mesh_layer_5_mat_override_Davy_Eyes_Dead_6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout davy_B_LoD_Switch_opt0_Cap_State_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 3, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 29981),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_TRANSPARENT, 34, 0, 0, davy_Butt_mesh_layer_1),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_TRANSPARENT, davy_Torso_skinned_mesh_layer_1),
					GEO_ASM(0, geo_move_mario_part_from_parent),
					GEO_ASM(0, geo_mario_tilt_torso),
					GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 66, 0, 0, davy_Torso_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
							GEO_OPEN_NODE(),
								GEO_NODE_START(),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, davy_Scarf_DL_mesh_layer_1),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, davy_Scarf_DL_mesh_layer_4),
								GEO_CLOSE_NODE(),
								GEO_BRANCH(1, davy_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_davy_Capless_Head),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 155, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(0, geo_mario_head_rotation),
								GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_TRANSPARENT, davy_Head_DL_mesh_layer_1),
											GEO_DISPLAY_LIST(LAYER_TRANSPARENT, davy_Head_DL_mesh_layer_5),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, davy_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Eye_State_Switch_opt1),
										GEO_BRANCH(1, davy_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Eye_State_Switch_opt2),
										GEO_BRANCH(1, davy_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Eye_State_Switch_opt3),
										GEO_BRANCH(1, davy_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Eye_State_Switch_opt4),
										GEO_BRANCH(1, davy_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Eye_State_Switch_opt5),
										GEO_BRANCH(1, davy_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Eye_State_Switch_opt6),
										GEO_BRANCH(1, davy_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Eye_State_Switch_opt7),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 110, -10, 99, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, davy_Left_Arm_Color_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, davy_Left_Forearm_skinned_mesh_layer_1),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 115, 0, 0, davy_Left_Forearm_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(1, geo_switch_mario_hand),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 120, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(1, geo_mario_hand_foot_scaler),
													GEO_SCALE(LAYER_FORCE, 65536),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_TRANSPARENT, davy_Left_Hand_DL_mesh_layer_1),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, davy_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_davy_Left_Hand_Open),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 110, -10, -99, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, davy_Right_Arm_Color_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, davy_Right_Forearm_skinned_mesh_layer_1),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 115, 0, 0, davy_Right_Forearm_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_hand),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 120, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(0, geo_mario_hand_foot_scaler),
													GEO_SCALE(LAYER_FORCE, 65536),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_TRANSPARENT, davy_Right_Hand_DL_mesh_layer_1),
													GEO_CLOSE_NODE(),
													GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, davy_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_davy_Right_Hand_Open),
											GEO_BRANCH(1, davy_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_davy_Right_Hand_Peace),
											GEO_BRANCH(1, davy_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_davy_Right_Hand_Cap),
											GEO_BRANCH(1, davy_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_davy_Right_Hand_Wing_Cap),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, -31, 7, 57, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, davy_Left_Thigh_Color_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, davy_Left_Thigh_Color_mesh_layer_5),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 189, 0, 0, davy_Left_Leg_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 152, 0, 0, davy_Left_Shoe_mesh_layer_1),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, -31, 7, -57, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, davy_Right_Thigh_Color_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, davy_Right_Thigh_Color_mesh_layer_5),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 189, 0, 0, davy_Right_Leg_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 152, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ASM(2, geo_mario_hand_foot_scaler),
									GEO_SCALE(LAYER_FORCE, 65536),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, davy_Right_Shoe_DL_mesh_layer_1),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout davy_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Eye_State_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, davy_Head_DL_mesh_layer_1_mat_override_Davy_Eyes_Half_0),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, davy_Head_DL_mesh_layer_5_mat_override_Davy_Eyes_Half_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout davy_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Eye_State_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, davy_Head_DL_mesh_layer_1_mat_override_Davy_Eyes_Closed_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, davy_Head_DL_mesh_layer_5_mat_override_Davy_Eyes_Closed_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout davy_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Eye_State_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, davy_Head_DL_mesh_layer_1_mat_override_Davy_Eyes_Left_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, davy_Head_DL_mesh_layer_5_mat_override_Davy_Eyes_Left_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout davy_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Eye_State_Switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, davy_Head_DL_mesh_layer_1_mat_override_Davy_Eyes_Right_3),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, davy_Head_DL_mesh_layer_5_mat_override_Davy_Eyes_Right_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout davy_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Eye_State_Switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, davy_Head_DL_mesh_layer_1_mat_override_Davy_Eyes_Up_4),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, davy_Head_DL_mesh_layer_5_mat_override_Davy_Eyes_Up_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout davy_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Eye_State_Switch_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, davy_Head_DL_mesh_layer_1_mat_override_Davy_Eyes_Down_5),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, davy_Head_DL_mesh_layer_5_mat_override_Davy_Eyes_Down_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout davy_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Eye_State_Switch_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, davy_Head_DL_mesh_layer_1_mat_override_Davy_Eyes_Dead_6),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, davy_Head_DL_mesh_layer_5_mat_override_Davy_Eyes_Dead_6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout davy_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(99, 180, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 35814),
			GEO_OPEN_NODE(),
				GEO_ASM(LAYER_OPAQUE + 3, geo_mario_set_player_colors),
				GEO_ASM(LAYER_OPAQUE_DECAL + 3, geo_mario_set_player_colors),
				GEO_ASM(LAYER_ALPHA + 3, geo_mario_set_player_colors),
				GEO_ASM(LAYER_TRANSPARENT + 3, geo_mario_set_player_colors),
				GEO_ASM(LAYER_TRANSPARENT_DECAL + 3, geo_mario_set_player_colors),
				GEO_ASM(LAYER_OPAQUE << 2, geo_mirror_mario_backface_culling),
				GEO_ASM(LAYER_OPAQUE_DECAL << 2, geo_mirror_mario_backface_culling),
				GEO_ASM(LAYER_ALPHA << 2, geo_mirror_mario_backface_culling),
				GEO_ASM(LAYER_TRANSPARENT << 2, geo_mirror_mario_backface_culling),
				GEO_ASM(LAYER_TRANSPARENT_DECAL << 2, geo_mirror_mario_backface_culling),
				GEO_ASM(0, geo_mirror_mario_set_alpha),
				GEO_SWITCH_CASE(0, geo_switch_mario_stand_run),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_SWITCH_CASE(0, geo_switch_mario_cap_effect),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 3, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_SCALE(LAYER_FORCE, 29981),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 34, 0, 0, davy_Butt_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, davy_Torso_skinned_mesh_layer_1),
											GEO_ASM(0, geo_move_mario_part_from_parent),
											GEO_ASM(0, geo_mario_tilt_torso),
											GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 66, 0, 0, davy_Torso_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
													GEO_OPEN_NODE(),
														GEO_NODE_START(),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_OPAQUE, davy_Scarf_DL_mesh_layer_1),
															GEO_DISPLAY_LIST(LAYER_ALPHA, davy_Scarf_DL_mesh_layer_4),
														GEO_CLOSE_NODE(),
														GEO_BRANCH(1, davy_Capless_Head),
													GEO_CLOSE_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 155, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(0, geo_mario_head_rotation),
														GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
														GEO_OPEN_NODE(),
															GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
															GEO_OPEN_NODE(),
																GEO_NODE_START(),
																GEO_OPEN_NODE(),
																	GEO_DISPLAY_LIST(LAYER_OPAQUE, davy_Head_DL_mesh_layer_1),
																	GEO_DISPLAY_LIST(LAYER_TRANSPARENT, davy_Head_DL_mesh_layer_5),
																GEO_CLOSE_NODE(),
																GEO_BRANCH(1, davy_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Eye_State_Switch_opt1),
																GEO_BRANCH(1, davy_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Eye_State_Switch_opt2),
																GEO_BRANCH(1, davy_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Eye_State_Switch_opt3),
																GEO_BRANCH(1, davy_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Eye_State_Switch_opt4),
																GEO_BRANCH(1, davy_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Eye_State_Switch_opt5),
																GEO_BRANCH(1, davy_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Eye_State_Switch_opt6),
																GEO_BRANCH(1, davy_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Eye_State_Switch_opt7),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 110, -10, 99, NULL),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, davy_Left_Arm_Color_mesh_layer_1),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_OPAQUE, davy_Left_Forearm_skinned_mesh_layer_1),
															GEO_ANIMATED_PART(LAYER_OPAQUE, 115, 0, 0, davy_Left_Forearm_mesh_layer_1),
															GEO_OPEN_NODE(),
																GEO_SWITCH_CASE(1, geo_switch_mario_hand),
																GEO_OPEN_NODE(),
																	GEO_NODE_START(),
																	GEO_OPEN_NODE(),
																		GEO_ANIMATED_PART(LAYER_OPAQUE, 120, 0, 0, NULL),
																		GEO_OPEN_NODE(),
																			GEO_ASM(1, geo_mario_hand_foot_scaler),
																			GEO_SCALE(LAYER_FORCE, 65536),
																			GEO_OPEN_NODE(),
																				GEO_DISPLAY_LIST(LAYER_OPAQUE, davy_Left_Hand_DL_mesh_layer_1),
																			GEO_CLOSE_NODE(),
																		GEO_CLOSE_NODE(),
																	GEO_CLOSE_NODE(),
																	GEO_BRANCH(1, davy_Left_Hand_Open),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 110, -10, -99, NULL),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, davy_Right_Arm_Color_mesh_layer_1),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_OPAQUE, davy_Right_Forearm_skinned_mesh_layer_1),
															GEO_ANIMATED_PART(LAYER_OPAQUE, 115, 0, 0, davy_Right_Forearm_mesh_layer_1),
															GEO_OPEN_NODE(),
																GEO_SWITCH_CASE(0, geo_switch_mario_hand),
																GEO_OPEN_NODE(),
																	GEO_NODE_START(),
																	GEO_OPEN_NODE(),
																		GEO_ANIMATED_PART(LAYER_OPAQUE, 120, 0, 0, NULL),
																		GEO_OPEN_NODE(),
																			GEO_ASM(0, geo_mario_hand_foot_scaler),
																			GEO_SCALE(LAYER_FORCE, 65536),
																			GEO_OPEN_NODE(),
																				GEO_DISPLAY_LIST(LAYER_OPAQUE, davy_Right_Hand_DL_mesh_layer_1),
																			GEO_CLOSE_NODE(),
																			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
																		GEO_CLOSE_NODE(),
																	GEO_CLOSE_NODE(),
																	GEO_BRANCH(1, davy_Right_Hand_Open),
																	GEO_BRANCH(1, davy_Right_Hand_Peace),
																	GEO_BRANCH(1, davy_Right_Hand_Cap),
																	GEO_BRANCH(1, davy_Right_Hand_Wing_Cap),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, -31, 7, 57, NULL),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, davy_Left_Thigh_Color_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, davy_Left_Thigh_Color_mesh_layer_5),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 189, 0, 0, davy_Left_Leg_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 152, 0, 0, davy_Left_Shoe_mesh_layer_1),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, -31, 7, -57, NULL),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, davy_Right_Thigh_Color_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, davy_Right_Thigh_Color_mesh_layer_5),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 189, 0, 0, davy_Right_Leg_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 152, 0, 0, NULL),
														GEO_OPEN_NODE(),
															GEO_ASM(2, geo_mario_hand_foot_scaler),
															GEO_SCALE(LAYER_FORCE, 65536),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_OPAQUE, davy_Right_Shoe_DL_mesh_layer_1),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_BRANCH(1, davy_B_LoD_Switch_opt0_Cap_State_Switch_opt1),
							GEO_BRANCH(1, davy_Magma_Davy),
							GEO_BRANCH(1, davy_Magma_Davy),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ASM((LAYER_OPAQUE << 2) | 1, geo_mirror_mario_backface_culling),
				GEO_ASM((LAYER_OPAQUE_DECAL << 2) | 1, geo_mirror_mario_backface_culling),
				GEO_ASM((LAYER_ALPHA << 2) | 1, geo_mirror_mario_backface_culling),
				GEO_ASM((LAYER_TRANSPARENT << 2) | 1, geo_mirror_mario_backface_culling),
				GEO_ASM((LAYER_TRANSPARENT_DECAL << 2) | 1, geo_mirror_mario_backface_culling),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, davy_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, davy_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, davy_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
