extern const GeoLayout j_cap_Normal_Cap_State_Switch_opt1[];
extern const GeoLayout j_cap_Normal_Cap_State_Switch_opt2[];
extern const GeoLayout j_cap_Normal_Cap_State_Switch_opt3[];
extern const GeoLayout j_cap_geo[];
extern Lights1 j_cap_J__EMBLEM__lights;
extern Lights1 j_cap_Cap_Bottom__CAP__lights;
extern Lights1 j_cap_Hat__CAP__lights;
extern Lights1 j_cap_Logo__CAP__lights;
extern Lights1 j_cap_Metal__METAL__lights;
extern u8 j_cap_letter_rgba16_alpha_rgba16[];
extern u8 j_cap_jer_shade_alpha_ia8[];
extern u8 j_cap_logo2_rgba16_alpha_ia8[];
extern u8 j_cap_Metal_Shade_rgba16_rgba16[];
extern u8 j_cap_Metal_Light_rgba16_rgba16[];
extern Vtx j_cap_Normal_Cap_DL_mesh_layer_1_vtx_0[6];
extern Gfx j_cap_Normal_Cap_DL_mesh_layer_1_tri_0[];
extern Vtx j_cap_Normal_Cap_DL_mesh_layer_1_vtx_1[9];
extern Gfx j_cap_Normal_Cap_DL_mesh_layer_1_tri_1[];
extern Vtx j_cap_Normal_Cap_DL_mesh_layer_1_vtx_2[36];
extern Gfx j_cap_Normal_Cap_DL_mesh_layer_1_tri_2[];
extern Vtx j_cap_Normal_Cap_DL_mesh_layer_4_vtx_0[6];
extern Gfx j_cap_Normal_Cap_DL_mesh_layer_4_tri_0[];
extern Gfx mat_j_cap_J__EMBLEM_[];
extern Gfx mat_j_cap_Cap_Bottom__CAP_[];
extern Gfx mat_j_cap_Hat__CAP_[];
extern Gfx mat_j_cap_Logo__CAP_[];
extern Gfx mat_j_cap_Metal__METAL_[];
extern Gfx mat_revert_j_cap_Metal__METAL_[];
extern Gfx j_cap_Normal_Cap_DL_mesh_layer_1[];
extern Gfx j_cap_Normal_Cap_DL_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx j_cap_Normal_Cap_DL_mesh_layer_4[];
extern Gfx j_cap_Normal_Cap_DL_mesh_layer_4_mat_override_Metal__METAL__0[];
extern Gfx j_cap_material_revert_render_settings[];
