extern const GeoLayout j_cap_Normal_Cap_State_Switch_opt1[];
extern const GeoLayout j_cap_geo[];
extern Lights1 j_cap_J__EMBLEM__lights;
extern Lights1 j_cap_Cap_Bottom__CAP__lights;
extern Lights1 j_cap_Hat__CAP__lights;
extern Lights1 j_cap_Logo__CAP__lights;
extern u8 j_cap_j_emblem_ia8[];
extern u8 j_cap_emblem_fill_i8[];
extern Vtx j_cap_Normal_Cap_DL_mesh_layer_1_vtx_0[6];
extern Gfx j_cap_Normal_Cap_DL_mesh_layer_1_tri_0[];
extern Vtx j_cap_Normal_Cap_DL_mesh_layer_1_vtx_1[9];
extern Gfx j_cap_Normal_Cap_DL_mesh_layer_1_tri_1[];
extern Vtx j_cap_Normal_Cap_DL_mesh_layer_1_vtx_2[36];
extern Gfx j_cap_Normal_Cap_DL_mesh_layer_1_tri_2[];
extern Vtx j_cap_Normal_Cap_DL_mesh_layer_4_vtx_0[6];
extern Gfx j_cap_Normal_Cap_DL_mesh_layer_4_tri_0[];
extern Gfx mat_j_cap_J__EMBLEM_[];
extern Gfx mat_j_cap_Cap_Bottom__CAP_[];
extern Gfx mat_j_cap_Hat__CAP_[];
extern Gfx mat_j_cap_Logo__CAP_[];
extern Gfx j_cap_Normal_Cap_DL_mesh_layer_1[];
extern Gfx j_cap_Normal_Cap_DL_mesh_layer_4[];
extern Gfx j_cap_material_revert_render_settings[];
