extern const GeoLayout metal_flower_Metal_Cap_State_Switch_opt1[];
extern const GeoLayout metal_flower_Metal_Cap_State_Switch_opt2[];
extern const GeoLayout metal_flower_Metal_Cap_State_Switch_opt3[];
extern const GeoLayout metal_flower_geo[];
extern Lights1 metal_flower_Metal_Flower_Stem_lights;
extern Lights1 metal_flower_Jer_Metal_METAL_lights;
extern u8 metal_flower_custom_mario_metal_base_rgba16_rgba16[];
extern u8 metal_flower_custom_mario_metal_shine_rgba16_rgba16[];
extern u8 metal_flower_metalflowereyes_ia8[];
extern Vtx metal_flower_Metal_Cap_DL_mesh_layer_1_vtx_0[141];
extern Gfx metal_flower_Metal_Cap_DL_mesh_layer_1_tri_0[];
extern Vtx metal_flower_Metal_Cap_DL_mesh_layer_1_vtx_1[112];
extern Gfx metal_flower_Metal_Cap_DL_mesh_layer_1_tri_1[];
extern Vtx metal_flower_Metal_Cap_DL_mesh_layer_4_vtx_0[6];
extern Gfx metal_flower_Metal_Cap_DL_mesh_layer_4_tri_0[];
extern Gfx mat_metal_flower_Metal_Flower_Stem[];
extern Gfx mat_metal_flower_Jer_Metal_METAL[];
extern Gfx mat_revert_metal_flower_Jer_Metal_METAL[];
extern Gfx mat_metal_flower_Metal_Flower_Eyes_Texture[];
extern Gfx mat_revert_metal_flower_Metal_Flower_Eyes_Texture[];
extern Gfx metal_flower_Metal_Cap_DL_mesh_layer_1[];
extern Gfx metal_flower_Metal_Cap_DL_mesh_layer_1_mat_override_Jer_Metal_METAL_0[];
extern Gfx metal_flower_Metal_Cap_DL_mesh_layer_4[];
extern Gfx metal_flower_Metal_Cap_DL_mesh_layer_4_mat_override_Jer_Metal_METAL_0[];
extern Gfx metal_flower_material_revert_render_settings[];
