extern const GeoLayout ice_flower_Metal_Cap_State_Switch_opt1[];
extern const GeoLayout ice_flower_geo[];
extern Lights1 ice_flower_Ice_Flower_Stem_lights;
extern Lights1 ice_flower_Metal__METAL__001_lights;
extern Lights1 ice_flower_Ice_Flower_Eyes_Texture_layer4_lights;
extern u8 ice_flower_jess_ice_shine_rgba16[];
extern u8 ice_flower_jess_ice_base_rgba16[];
extern u8 ice_flower_iceflowereyes_ia8[];
extern Vtx ice_flower_Metal_Cap_DL_mesh_layer_1_vtx_0[141];
extern Gfx ice_flower_Metal_Cap_DL_mesh_layer_1_tri_0[];
extern Vtx ice_flower_Metal_Cap_DL_mesh_layer_1_vtx_1[43];
extern Gfx ice_flower_Metal_Cap_DL_mesh_layer_1_tri_1[];
extern Vtx ice_flower_Metal_Cap_DL_mesh_layer_4_vtx_0[6];
extern Gfx ice_flower_Metal_Cap_DL_mesh_layer_4_tri_0[];
extern Gfx mat_ice_flower_Ice_Flower_Stem[];
extern Gfx mat_ice_flower_Metal__METAL__001[];
extern Gfx mat_revert_ice_flower_Metal__METAL__001[];
extern Gfx mat_ice_flower_Ice_Flower_Eyes_Texture_layer4[];
extern Gfx mat_revert_ice_flower_Ice_Flower_Eyes_Texture_layer4[];
extern Gfx ice_flower_Metal_Cap_DL_mesh_layer_1[];
extern Gfx ice_flower_Metal_Cap_DL_mesh_layer_4[];
extern Gfx ice_flower_material_revert_render_settings[];
