extern const GeoLayout jj_cap_davy_magma_6_Cap_Anim_State_Switch_opt1[];
extern const GeoLayout jj_cap_davy_magma_geo[];
extern Lights1 jj_cap_davy_magma_Magma_Flower_Stem_lights;
extern Lights1 jj_cap_davy_magma_Magma_Flower_Leaf_lights;
extern u8 jj_cap_davy_magma_DavyMagma_rgba16[];
extern u8 jj_cap_davy_magma_FlowerEyesMagma_rgba16[];
extern u8 jj_cap_davy_magma_FlowerLeaves_rgba16[];
extern Vtx jj_cap_davy_magma_Metal_Cap_DL_mesh_layer_1_vtx_0[21];
extern Gfx jj_cap_davy_magma_Metal_Cap_DL_mesh_layer_1_tri_0[];
extern Vtx jj_cap_davy_magma_Metal_Cap_DL_mesh_layer_1_vtx_1[45];
extern Gfx jj_cap_davy_magma_Metal_Cap_DL_mesh_layer_1_tri_1[];
extern Vtx jj_cap_davy_magma_Metal_Cap_DL_mesh_layer_5_vtx_0[6];
extern Gfx jj_cap_davy_magma_Metal_Cap_DL_mesh_layer_5_tri_0[];
extern Vtx jj_cap_davy_magma_Metal_Cap_DL_mesh_layer_4_vtx_0[15];
extern Gfx jj_cap_davy_magma_Metal_Cap_DL_mesh_layer_4_tri_0[];
extern Gfx mat_jj_cap_davy_magma_Magma_Flower_Stem[];
extern Gfx mat_jj_cap_davy_magma_Magma[];
extern Gfx mat_revert_jj_cap_davy_magma_Magma[];
extern Gfx mat_jj_cap_davy_magma_Magma_Flower_Eyes[];
extern Gfx mat_revert_jj_cap_davy_magma_Magma_Flower_Eyes[];
extern Gfx mat_jj_cap_davy_magma_Magma_Flower_Leaf[];
extern Gfx mat_revert_jj_cap_davy_magma_Magma_Flower_Leaf[];
extern Gfx jj_cap_davy_magma_Metal_Cap_DL_mesh_layer_1[];
extern Gfx jj_cap_davy_magma_Metal_Cap_DL_mesh_layer_5[];
extern Gfx jj_cap_davy_magma_Metal_Cap_DL_mesh_layer_4[];
extern Gfx jj_cap_davy_magma_material_revert_render_settings[];
