extern const GeoLayout beach_flower_Normal_Cap_State_Switch_opt1[];
extern const GeoLayout beach_flower_geo[];
extern Lights1 beach_flower_Headband_lights;
extern Lights1 beach_flower_Flower_Petals__CAP__lights;
extern Lights1 beach_flower_Flower_Center__EMBLEM__lights;
extern Vtx beach_flower_Normal_Cap_DL_mesh_layer_1_vtx_0[12];
extern Gfx beach_flower_Normal_Cap_DL_mesh_layer_1_tri_0[];
extern Vtx beach_flower_Normal_Cap_DL_mesh_layer_1_vtx_1[70];
extern Gfx beach_flower_Normal_Cap_DL_mesh_layer_1_tri_1[];
extern Vtx beach_flower_Normal_Cap_DL_mesh_layer_1_vtx_2[9];
extern Gfx beach_flower_Normal_Cap_DL_mesh_layer_1_tri_2[];
extern Gfx mat_beach_flower_Headband[];
extern Gfx mat_revert_beach_flower_Headband[];
extern Gfx mat_beach_flower_Flower_Petals__CAP_[];
extern Gfx mat_beach_flower_Flower_Center__EMBLEM_[];
extern Gfx beach_flower_Normal_Cap_DL_mesh_layer_1[];
extern Gfx beach_flower_material_revert_render_settings[];
